name: linting, testing, building

on: 
  push: 
    branches: [master]
  pull_request:
    branches:  [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }} 
      - name: Install dependencies
        run: npm install
      - name: Build production
        run: yarn build:prod
        if: always()
      - name: Linting typescript
        run: npm run lint:ts
        if: always()
      - name: Linting scss
        run: npm run lint:scss
        if: always()
      - name: Unit test
        run: npm run test:unit
        if: always()
      - name: Build storybook
        run: yarn build:storybook
      - name: Loki test
        run: npm run test:ui:ci
        
         
